language: node_js
sudo: false
dist: bionic
node_js:
- '10'
- '12'
install:
- npm install
- pip install --user awscli
script:
- npm run build
after_success:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "release" ]]; then
    npm run rebuild-docker-image;
    npm config set //registry.npmjs.org/:_authToken="$NPM_TOKEN";
    npm publish;
  fi
notifications:
  email:
    on_success: never
    on_failure: always
